### ISSUE TITLE
Can you provider full source code of demo

### ISSUE THREAD

**Issue by winneryong** [rauluranga/Cocos2dx-UIKit#1]
Hi, can you provider full source code of  video demo, i want study it. thanks!

**Comment by rauluranga** [comment]
What is missing??

**Comment by winneryong** [comment]
oh!, I'm sorry ,i not  check out code!  some code in proj.ios_mac directory. i not see them. thanks for your share! have good day.

**Comment by rauluranga** [comment]
so everything is fine??

**Comment by winneryong** [comment]
Yes, is running. everything is fine.
