### ISSUE TITLE
crash when popViewControllerAnimated

### ISSUE THREAD

**Issue by Odinysus** [rauluranga/Cocos2dx-UIKit#2]
I do it follow the project, but when I popViewController int the Lis_listener in rootViewController(I push rootViewController in a normal viewController ).like this 
        cocos2d::EventListenerCustom *_listener =            cocos2d::EventListenerCustom::create("game_custom_event1", [=](cocos2d::EventCustom* event){

```
    [self.navigationController popViewControllerAnimated:YES];
});
```

then I it run this 
       - (void)viewDidDisappear:(BOOL)animated {
               [_eaglView release];
              _eaglView = nil;
              }
it doesn't mater,but crash after that. plz help

**Comment by rauluranga** [comment]
do you have the example?

**Comment by Odinysus** [comment]
oh,I has found that is cocos2d-x's bug which  CCFrameBuffer is not fully deallocated. And you found this bug.Thanks

**Comment by rauluranga** [comment]
nice! =)
