### ISSUE TITLE
when set CCEAGLView multiSampling:YES, there is only a pink screen in game view

### ISSUE THREAD

**Issue by vanferry** [rauluranga/Cocos2dx-UIKit#5]
Hi, I really appreciate this Cocos2dx-UIKit example, this will make my app easily ported to most of the platforms. Since I'm making a 2d graphics app, I need to set CCEAGLView multiSampling:YES to get better graphics result, 

I Change 
    CCEAGLView __ccEAGLView = [CCEAGLView viewWithFrame: [[UIScreen mainScreen] bounds]
                                         pixelFormat: (NSString_)cocos2d::GLViewImpl::_pixelFormat
                                         depthFormat: cocos2d::GLViewImpl::_depthFormat
                                  preserveBackbuffer: NO
                                          sharegroup: nil
                                       multiSampling: NO  ----> YES
                                     numberOfSamples: 0 ];

Then there is only a pink screen and I get countless log as follow:

libpng warning: iCCP: known incorrect sRGB profile
2016-10-03 16:02:05.447 Cocos2dx-UIKit-mobile[38855:2131546] cocos2d: surface size: 1242x2208
OpenGL error 0x0502 in -[CCEAGLView swapBuffers] 324
OpenGL error 0x0502 in -[CCEAGLView swapBuffers] 324
OpenGL error 0x0502 in -[CCEAGLView swapBuffers] 324
OpenGL error 0x0502 in -[CCEAGLView swapBuffers] 324
......

Do you know how to get both integration and multiSampling working? Thanks in advance.

**Comment by rauluranga** [comment]
Hi @vanferry!
I think you should open an issue on the [Cocos2d-x](https://github.com/cocos2d/cocos2d-x) main repository.

**Comment by vanferry** [comment]
Thanks. I'll open one.

**Comment by vanferry** [comment]
I found the solution, I didn't use mutilsampling the right way, it should be:

CCEAGLView _ccEAGLView = [CCEAGLView viewWithFrame: [[UIScreen mainScreen] bounds]
pixelFormat: (NSString)cocos2d::GLViewImpl::_pixelFormat
depthFormat: cocos2d::GLViewImpl::_depthFormat
preserveBackbuffer: NO
sharegroup: nil
multiSampling: NO ----> YES
numberOfSamples: 0 -----> 4 ];

Both last two lines are needed, now it's fine.
